// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/bgpconfig/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BgpConfigLister helps list BgpConfigs.
type BgpConfigLister interface {
	// List lists all BgpConfigs in the indexer.
	List(selector labels.Selector) (ret []*v1.BgpConfig, err error)
	// BgpConfigs returns an object that can list and get BgpConfigs.
	BgpConfigs(namespace string) BgpConfigNamespaceLister
	BgpConfigListerExpansion
}

// bgpConfigLister implements the BgpConfigLister interface.
type bgpConfigLister struct {
	indexer cache.Indexer
}

// NewBgpConfigLister returns a new BgpConfigLister.
func NewBgpConfigLister(indexer cache.Indexer) BgpConfigLister {
	return &bgpConfigLister{indexer: indexer}
}

// List lists all BgpConfigs in the indexer.
func (s *bgpConfigLister) List(selector labels.Selector) (ret []*v1.BgpConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.BgpConfig))
	})
	return ret, err
}

// BgpConfigs returns an object that can list and get BgpConfigs.
func (s *bgpConfigLister) BgpConfigs(namespace string) BgpConfigNamespaceLister {
	return bgpConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BgpConfigNamespaceLister helps list and get BgpConfigs.
type BgpConfigNamespaceLister interface {
	// List lists all BgpConfigs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.BgpConfig, err error)
	// Get retrieves the BgpConfig from the indexer for a given namespace and name.
	Get(name string) (*v1.BgpConfig, error)
	BgpConfigNamespaceListerExpansion
}

// bgpConfigNamespaceLister implements the BgpConfigNamespaceLister
// interface.
type bgpConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BgpConfigs in the indexer for a given namespace.
func (s bgpConfigNamespaceLister) List(selector labels.Selector) (ret []*v1.BgpConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.BgpConfig))
	})
	return ret, err
}

// Get retrieves the BgpConfig from the indexer for a given namespace and name.
func (s bgpConfigNamespaceLister) Get(name string) (*v1.BgpConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("bgpconfig"), name)
	}
	return obj.(*v1.BgpConfig), nil
}
