// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	bgpconfigv1 "github.com/contiv/vpp/plugins/crd/pkg/apis/bgpconfig/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBgpConfigs implements BgpConfigInterface
type FakeBgpConfigs struct {
	Fake *FakeBgpconfigV1
	ns   string
}

var bgpconfigsResource = schema.GroupVersionResource{Group: "bgpconfig.contiv.vpp", Version: "v1", Resource: "bgpconfigs"}

var bgpconfigsKind = schema.GroupVersionKind{Group: "bgpconfig.contiv.vpp", Version: "v1", Kind: "BgpConfig"}

// Get takes name of the bgpConfig, and returns the corresponding bgpConfig object, and an error if there is any.
func (c *FakeBgpConfigs) Get(name string, options v1.GetOptions) (result *bgpconfigv1.BgpConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bgpconfigsResource, c.ns, name), &bgpconfigv1.BgpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgpconfigv1.BgpConfig), err
}

// List takes label and field selectors, and returns the list of BgpConfigs that match those selectors.
func (c *FakeBgpConfigs) List(opts v1.ListOptions) (result *bgpconfigv1.BgpConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bgpconfigsResource, bgpconfigsKind, c.ns, opts), &bgpconfigv1.BgpConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &bgpconfigv1.BgpConfigList{ListMeta: obj.(*bgpconfigv1.BgpConfigList).ListMeta}
	for _, item := range obj.(*bgpconfigv1.BgpConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bgpConfigs.
func (c *FakeBgpConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bgpconfigsResource, c.ns, opts))

}

// Create takes the representation of a bgpConfig and creates it.  Returns the server's representation of the bgpConfig, and an error, if there is any.
func (c *FakeBgpConfigs) Create(bgpConfig *bgpconfigv1.BgpConfig) (result *bgpconfigv1.BgpConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bgpconfigsResource, c.ns, bgpConfig), &bgpconfigv1.BgpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgpconfigv1.BgpConfig), err
}

// Update takes the representation of a bgpConfig and updates it. Returns the server's representation of the bgpConfig, and an error, if there is any.
func (c *FakeBgpConfigs) Update(bgpConfig *bgpconfigv1.BgpConfig) (result *bgpconfigv1.BgpConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bgpconfigsResource, c.ns, bgpConfig), &bgpconfigv1.BgpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgpconfigv1.BgpConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBgpConfigs) UpdateStatus(bgpConfig *bgpconfigv1.BgpConfig) (*bgpconfigv1.BgpConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bgpconfigsResource, "status", c.ns, bgpConfig), &bgpconfigv1.BgpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgpconfigv1.BgpConfig), err
}

// Delete takes name of the bgpConfig and deletes it. Returns an error if one occurs.
func (c *FakeBgpConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bgpconfigsResource, c.ns, name), &bgpconfigv1.BgpConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBgpConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bgpconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &bgpconfigv1.BgpConfigList{})
	return err
}

// Patch applies the patch and returns the patched bgpConfig.
func (c *FakeBgpConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *bgpconfigv1.BgpConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bgpconfigsResource, c.ns, name, data, subresources...), &bgpconfigv1.BgpConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgpconfigv1.BgpConfig), err
}
